@startuml classDiagram

    ' use text-base attributes icon
    skinparam classAttributeIconSize 0
    ' hide class icon
    hide circle

    'skinparam linetype ortho
    'skinparam linetype polyline

    skinparam nodesep 100
    'skinparam ranksep 100

    'skinparam classBackgroundColor #d0b6eb
    'skinparam ClassFontSize 10 

    User <|-- Customer
    User <|-- Admin
    Customer <|-- Musician
    Customer <|-- Organizer


    class User {
        -user_id
        -salt
        -password_hash
        +verify(password)
        +login()
    }

    class Admin {
        -staff_id
        
    }

    class Customer {
        -customer_id
        -first_name
        -last_name
        -phone_number
        -email
        -calendar_color
        -calendar_style
        -calendar_font_size
        +change calendar preference()
        +change account detail()
        +send message(chatroom_id)
    }

    class Musician {
        -status
        -specialty[0..*]
        -profile_picture
        -introduction
        -link
        -latitute
        -longitude
        -sub_district
        -district
        -province
        -zip_code
        -picture_uri[0..*]
        +edit portfolio()
        +accept event request()
        +decline event request()
    }
    'User "1..1" -- "1..1\t" Credential: authenticate <

    class Portfolio {
        -link
        -text
        -profile_picture
        -picture_uri
    }
    Musician "1..1" *-- "1..1" Portfolio: is Part of <
    Portfolio "1..1" -- "0..*\t" Event: history <


    class Organizer {
        -company
        +search musician (event_details[0..*])
        +create chatroom()
        +create event request(event_details[0..*])
        +confirm event completion(event_id)
        +create review(event_id)
    }

    class Event {
        -event_id
        -status
        -start_time
        -end_time
        -description
        -wage
        +update calendar()
        +create review()
        +create payment()
        +add to portfolio()
    }

    'Musician "1..1" -- "1..1" Location: live_at
    Musician "1..1" -- "0..*" Event: work >
    Event "0..*" -- "1..1" Location: at >
    Organizer "1..1" -- "0..*" Event: host >
    
    class Location {
        -location_id
        -longitude
        -latitude
        -sub_district
        -district
        -province
        -zip_code
    }

    class Review {
        -review_id
        -rating
        -comment
        -created_at
    }

    class Payment {
        -payment_id
        -status
        -transaction_id
        -method
        -timestamp
        -currency_type
        -amount
        -description
        +verify transaction()
    } 

    Event "1..1\t" o-- "1..1" Review: is Part Of <
    Event "1..1" o-- "1..*\t" Payment: is Part Of <

    Message <|-- Attachment
    Message <|-- Text
    Message <|-- EventRequest

    class Message {
        -message_no
        -sent_at
        -sender
    }

    class Attachment {
        -uri
    }

    class Text {
        -text
    }

    class EventRequest {
        -start_time
        -end_time
        -description
    }

    class ChatRoom {
        -chatroom_id
    } 
    
    ChatRoom "1..1" *-- "0..*\t" Message: is Part of <
    Event "1..*" - "1..1 " ChatRoom: chat >
    Organizer "1..1\t" -- "1..*" ChatRoom: chat >
    Musician "1..1" -- "1..*" ChatRoom: chat >

@enduml