classDiagram

    User <|-- Customer
    User <|-- Admin
    Customer <|-- Musician
    Customer <|-- Organizer

    class User {
        -user_id
    }
    
    class Admin {
        -staff_id
    }

    class Customer {
        -first_name
        -last_name
        -phone_number
        -email
        -calendar_color
        -calendar_style
        -calendar_font_size
    }

    class Musician {
        -status
        -specialty
    }

    class Credential {
        -salt
        -password_hash
    }
    User "1" -- "1" Credential: authenticate

    class Portfolio {
        -link
        -text
        -profile_picture
        -picture_uri
    }
    Musician *-- Portfolio
    Portfolio "1" -- "N" Event: history


    class Organizer {
        -company
        +makeEvent()
    }

    class Event {
        -event_id
        -start_time
        -end_time
        -description
    }

    Musician "1" -- "1" Location: live_at
    Musician "1" -- "N" Event: work
    Event "N" -- "1" Location: at
    Organizer "1" -- "N" Event: host
    
    class Location {
        -longitude
        -latitude
        -sub_district
        -district
        -province
        -zip_code
        +run()
    }

    class Review {
        -rating
        -comment
        -create_at
    }

    class Payment {
        -payment_id
        -status
    }

    Event "_" -- "1" Review: have
    Event "1" -- "_" Payment: have

    Message <|-- Attachment
    Message <|-- Text
    Message <|-- EventRequest

    class Message {
        -message_no
        -send_at
        -sender
    }

    class Attachment {
        -uri
    }

    class Text {
        -text
    }

    class EventRequest {
        -start_time
        -end_time
        -description
    }

    class ChatRoom {
        -chatroom_id
    }
    
    ChatRoom "1" -- "N" Message: contain
    Event "1" -- "1" ChatRoom: chat
    Musician "1" -- "1" ChatRoom: chat
