@startuml classDiagram

    ' use text-base attributes icon
    skinparam classAttributeIconSize 0
    ' hide class icon
    hide circle

    'skinparam linetype ortho
    'skinparam linetype polyline

    skinparam nodesep 100
    'skinparam ranksep 100

    'skinparam classBackgroundColor #d0b6eb
    'skinparam ClassFontSize 10 

    UserEntity <|-- CustomerEntity
    CustomerEntity <|-- MusicianEntity
    CustomerEntity <|-- OrganizerEntity
    MusicianEntity "1..1" *-- "1..1" PortfolioEntity: is Part of <
    PortfolioEntity "1..1" -- "0..*\t" EventEntity: history <

    'Musician "1..1" -- "1..1" Location: live_at
    MusicianEntity "1..1" -- "0..*" EventEntity: work >
    EventEntity "0..*" -- "1..1" LocationEntity: at >
    OrganizerEntity "1..1" -- "0..*" EventEntity: host >

    EventEntity "1..1\t" o-- "1..1" ReviewEntity: is Part Of <
    EventEntity "1..1" o-- "1..*\t" PaymentEntity: is Part Of <

    MessageEntity  <|-- AttachmentEntity
    MessageEntity  <|-- TextEntity
    MessageEntity  <|-- EventRequestEntity

    ChatRoomEntity "1..1" *-- "0..*\t" MessageEntity: is Part of <
    EventEntity "1..*" - "1..1 " ChatRoomEntity: chat >
    OrganizerEntity "1..1\t" -- "1..*" ChatRoomEntity: chat >
    MusicianEntity "1..1" -- "1..*" ChatRoomEntity: chat >

    UserHandler -- UserController
    UserController -- UserEntity
    EventHandler -- EventController
    EventController -- EventEntity
    PaymentHandler -- PaymentController
    PaymentController -- PaymentEntity
    


    class UserHandler <<Boundary>> {
        +login()
        +verify(password)
        +update password(new_password)
    }

    class UserController <<Control>> {
        +change password(new_password)
    }

    class UserEntity <<Entity>> {
        -user_id
        -salt
        -password_hash
    }

    class AdminEntity <<Entity>> {
        -staff_id
    }

    class AdminController <<Control>> {
        +manage review()
    }

    class AdminHandler <<Boundary>> {
        +update review()
    }

    class CustomerEntity <<Entity>> {
        -customer_id
        -first_name
        -last_name
        -phone_number
        -email
        -calendar_color
        -calendar_style
        -calendar_font_size
    }

    class CustomerController <<Control>> {
        +change calendar preference()
        +change account detail()
        +send message(chatroom_id)
    }

    class CustomerHandler <<Boundary>> {
        +update calendar preference()
        +update account detail()
    }

    class CalendarController <<Control>> {
        +manage related events()
    }

    class CalendarHandler <<Boundary>> {
        +fetch related events(customer_id)
    }

    class MusicianEntity <<Entity>> {
        -status
        -specialty[0..*]
        -profile_picture
        -introduction
        -link
        -latitute
        -longitude
        -sub_district
        -district
        -province
        -zip_code
        -picture_uri[0..*]
    }

    class MusicianController <<Control>> {
        +edit portfolio()
        +accept event request()
        +decline event request()
    }  

    'User "1..1" -- "1..1\t" Credential: authenticate <

    class PortfolioEntity <<Entity>> {
        -link
        -text
        -profile_picture
        -picture_uri
    }

    class PortfolioHandler <<Boundary>> {
        +update portfolio()
    }

    class OrganizerEntity <<Entity>> {
        -company
    }

    class OrganizerController <<Control>> {
        +search musician (event_details[0..*])
        +initiate chatroom(musicianId)
        +initiate event request(event_details[0..*])
        +confirm event completion(event_id)
        +create review(event_id)
    }

    class EventEntity <<Entity>> {
        -event_id
        -status
        -start_time
        -end_time
        -description
        -wage
    }

    class EventController <<Control>> {
        +add to portfolio()
    }       

    class EventHandler <<Boundary>> {
        +update calendar()
        +create review()
        +create payment()
    }

    class LocationEntity <<Entity>> {
        -location_id
        -longitude
        -latitude
        -sub_district
        -district
        -province
        -zip_code
    }

    class ReviewEntity <<Entity>> {
        -review_id
        -rating
        -comment
        -created_at
    }

    class ReviewHandler <<Boundary>> {
        +update review(reviewId)
    }

    class Payment <<Entity>>{
        -payment_id
        -status
        -transaction_id
        -method
        -timestamp
        -currency_type
        -amount
        -description
        +verify transaction()
    } 

    class MessageEntity <<Entity>> {
        -message_no
        -sent_at
        -sender
    }

    class AttachmentEntity <<Entity>> {
        -uri
    }

    class TextEntity <<Entity>> {
        -text
    }

    class EventRequestEntity <<Entity>> {
        -start_time
        -end_time
        -description
    }

    class EventRequestHandler <<Boundary>> {
        +update event request()
    }

    class ChatRoomEntity <<Entity>> {
        -chatroom_id
    } 
    
    class ChatRoomHandler <<Boundary>> {
        +create chatroom(organizerId, musicianId)
    }

@enduml